de.egladil.bv.jsf/src/main/java/de/egladil/bv/jsf/beans/Login.java
/**
 *
 */
package de.egladil.bv.jsf.beans;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

import org.apache.shiro.SecurityUtils;
import org.apache.shiro.authc.AuthenticationException;
import org.apache.shiro.authc.ExcessiveAttemptsException;
import org.apache.shiro.authc.UnknownAccountException;
import org.apache.shiro.authc.UsernamePasswordToken;
import org.apache.shiro.subject.Subject;
import org.apache.shiro.util.StringUtils;
import org.omnifaces.util.Faces;
import org.omnifaces.util.Messages;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.egladil.bv.jsf.exceptions.BVAuthenticationException;
import de.egladil.bv.jsf.exceptions.HoneypotException;
import de.egladil.bv.jsf.utils.FacesUtils;
import de.egladil.bv.jsf.utils.MessagesResource;
import de.egladil.bv.shiro_aas.domain.EgladilPrincipalCollection;
import de.egladil.bv.shiro_aas.entities.Benutzerkonto;
import de.egladil.bv.shiro_aas.impl.BenutzerServiceImpl;
import de.egladil.common.persistence.EgladilStorageException;

/**
 * @author heike
 *
 */
@Named
@SessionScoped
public class Login implements Serializable {

	private static final long serialVersionUID = 1L;

	private static final Logger LOG = LoggerFactory.getLogger(Login.class);

	public static final String BV_URL = "app/bvIndex.xhtml";

	private String username;

	private String password;

	private String kleber = "";

	@Inject
	private BenutzerServiceImpl benutzerService;

	/**
	 *
	 */

	public void submit() {
		try {
			if (StringUtils.hasText(kleber)) {
				throw new HoneypotException("EgladilHoneypotException: " + toHoneypotDetails());
			}
			// Hier wird jetzt über die shiro.ini der AuthenticationService bemüht
			UsernamePasswordToken token = new UsernamePasswordToken(username, password, false);
			SecurityUtils.getSubject().login(token);
			token.clear();

			Subject subject = SecurityUtils.getSubject();
			EgladilPrincipalCollection principals = (EgladilPrincipalCollection) subject.getPrincipals();

			String uuid = (String) principals.getPrimaryPrincipal();
			Benutzerkonto admin = benutzerService.loadBenutzerkontoByUuid(uuid);

			LOG.info("Admin {} hat sich eingeloggt", admin.getEmail());

			FacesUtils.setBenutzerkonto(admin);
			// Wenn man hier ist, gibt es keinen savedRequest, auf den umgeleitet werden könnte, da man direkt
			// mit der Login-Seite startet. Daher kann man hier direkt weiter in die BV
			Faces.redirect(BV_URL);
		} catch (EgladilStorageException | BVAuthenticationException e) {
			LOG.error(e.getMessage());
			String resourceText = MessagesResource.getInstance().getText("server.error");
			Messages.addGlobalError(resourceText);
		} catch (HoneypotException e) {
			LOG.warn(e.getMessage());
			String resourceText = MessagesResource.getInstance().getText("auth.login.honey");
			Messages.addGlobalError(resourceText);
		} catch (UnknownAccountException e) {
			LOG.debug(e.getMessage(), e);
			String resourceText = MessagesResource.getInstance().getText("auth.login.credentials");
			Messages.addGlobalError(resourceText);
		} catch (ExcessiveAttemptsException e) {
			LOG.warn(e.getMessage());
			String resourceText = MessagesResource.getInstance().getText("auth.login.bot");
			Messages.addGlobalError(resourceText);
		} catch (AuthenticationException e) {
			String resourceText = MessagesResource.getInstance().getText("auth.login.general");
			Messages.addGlobalError(resourceText);
			LOG.debug(e.getMessage(), e);
		} catch (Exception e) {
			LOG.error("Unerwartete Exception: " + e.getMessage(), e);
			String resourceText = MessagesResource.getInstance().getText("server.error");
			Messages.addGlobalError(resourceText);
		}
	}

	private String toHoneypotDetails() {
		HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
		String ipAddress = request.getHeader("X-FORWARDED-FOR");
		if (ipAddress == null) {
			ipAddress = request.getRemoteAddr();
		}
		return "Login [username=" + username + ", kleber=" + kleber + ", ipAddress=" + ipAddress + "]";
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the kleber
	 */
	public String getKleber() {
		return kleber;
	}

	/**
	 * @param kleber the kleber to set
	 */
	public void setKleber(String kleber) {
		this.kleber = kleber;
	}

	/**
	 * Rückgabe des Benutzernamens zur Anzeige im fisHeader.
	 *
	 * @return the logged in user name
	 */
	public String getLoggedInUserInfo() {
		Benutzerkonto admin = FacesUtils.getBenutzerkonto();
		if (admin != null) {
			return MessagesResource.getInstance().getText("header.userinfo.admin", admin.getEmail());
		}
		return MessagesResource.getInstance().getText("header.userinfo.anon");
	}
}

de.egladil.bv.jsf/src/main/java/de/egladil/bv/jsf/beans/Logout.java
/**
 *
 */
package de.egladil.bv.jsf.beans;

import java.io.IOException;
import java.io.Serializable;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

import org.apache.shiro.SecurityUtils;
import org.omnifaces.util.Faces;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import de.egladil.bv.jsf.utils.FacesUtils;
import de.egladil.bv.shiro_aas.entities.Benutzerkonto;

/**
 * @author heike
 *
 */
@Named
@RequestScoped
public class Logout implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7526371246088242806L;

	private static final Logger LOG = LoggerFactory.getLogger(Logout.class);

	public static final String HOME_URL = "index.xhtml";

	public void submit() throws IOException {
		Benutzerkonto admin = FacesUtils.getBenutzerkonto();
		String email = admin == null ? "null" : admin.getEmail();
		SecurityUtils.getSubject().logout();
		Faces.invalidateSession();
		LOG.info("Admin {} hat sich ausgeloggt", email);
		Faces.redirect(HOME_URL);
	}
}

de.egladil.bv.jsf/src/main/java/de/egladil/bv/jsf/rest/RESTClientBean.java
//=====================================================
// Projekt: de.egladil.bv.jsf
// (c) Heike Winkelvoß
//=====================================================

package de.egladil.bv.jsf.rest;

import java.io.Serializable;
import java.net.URI;

import javax.enterprise.context.ApplicationScoped;
import javax.ws.rs.client.Client;
import javax.ws.rs.client.ClientBuilder;
import javax.ws.rs.client.WebTarget;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.UriBuilder;

import org.glassfish.jersey.client.ClientConfig;

/**
 * RESTClientBean Kommuniziert mit diversen REST-Services.
 */
@ApplicationScoped
public class RESTClientBean implements Serializable {

	/* serialVersionUID */
	private static final long serialVersionUID = 1L;

	private static URI getBaseURI() {
		return UriBuilder.fromUri("http://localhost:9520/mkvadmin").build();
	}

	public void loadBenutzer() {
		ClientConfig config = new ClientConfig();
		Client client = ClientBuilder.newClient(config);
		WebTarget target = client.target(getBaseURI());

		// @formatter:off
		String response = target.path("session")
								.path("kontext")
								.request()
								.accept(MediaType.APPLICATION_JSON)
								.get(Response.class)
								.toString();
		// @formatter:on
		System.out.println(response);

	}

}

de.egladil.bv.jsf/src/main/webapp/app/bvIndex.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<h:body>
	<ui:composition template="../template/layout.xhtml">
		<ui:define name="content">
			<h2>#{lbl['page.subheader']}</h2>

			<h:commandButton id="btnCancel" value="#{lbl['button.cancel']}"
				immediate="true" />
			<h:form>
				<h:commandButton value="#{lbl['button.logout']}" action="#{logout.submit}" />
			</h:form>

		</ui:define>
	</ui:composition>
</h:body>
</html>

de.egladil.bv.jsf/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core">

<h:body>
	<ui:composition template="template/layout.xhtml">
		<ui:define name="content">


			<h2>#{lbl['heading.login']}</h2>
			<h:form id="login">
				<h:panelGrid columns="3">
					<h:outputLabel for="username" value="#{lbl['label.username']}" />
					<h:inputText id="username" value="#{login.username}"
						required="true">
						<f:ajax event="blur" render="m_username" />
					</h:inputText>
					<h:message id="m_username" for="username" />

					<h:outputLabel for="password" value="#{lbl['label.password']}" />
					<h:inputSecret id="password" value="#{login.password}"
						required="true">
						<f:ajax event="blur" render="m_password" />
					</h:inputSecret>
					<h:message id="m_password" for="password" />

					<h:panelGroup />
					<h:commandButton value="#{lbl['button.login']}" action="#{login.submit}">
						<f:ajax execute="@form" render="@form" />
					</h:commandButton>
					<h:messages globalOnly="true" layout="table" />
					<h:panelGroup styleClass="kleber">
						<h:outputLabel for="kleber"
							value="Diese URL wird nicht abgefragt. Tragen Sie hier bitte NICHTS ein" />
						<h:inputText id="kleber" value="#{login.kleber}" />
					</h:panelGroup>
				</h:panelGrid>
			</h:form>
		</ui:define>
	</ui:composition>
</h:body>
</html>

de.egladil.bv.jsf/src/main/webapp/template/default/bvHeader.xhtml
<ui:composition
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	<!-- <h:outputStylesheet library="css" name="hessen_examples.css" /> -->
	<h:form id="headerForm">
		<p:outputPanel id="bqHeaderPanel">
			<table style="width: 100%;">
				<tr>
					<td
						width="20%"
						style="text-align: left;">BV-Logo</td>
					<td
						width="40%"
						style="text-align: center;">BV Benutzerverwaltung</td>
					<td
						width="40%"
						style="text-align: right; vertical-align: bottom;"><h:outputText
							id="headeruserinfo"
							style="padding: 20px;"
							value="#{login.loggedInUserInfo}" /> <h:commandButton
							value="#{lbl['button.logout']}"
							action="#{logout.submit}" /></td>
				</tr>
			</table>
		</p:outputPanel>
	</h:form>
</ui:composition>

de.egladil.bv.jsf/src/main/webapp/template/layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<h:outputStylesheet library="css"  name="style.css" />
	<title>Egladil Benutzerverwaltung</title>
</h:head>
<h:body>

    <div id="header">
		<ui:insert name="header" >
		  <ui:include src="default/bvHeader.xhtml" />
		</ui:insert>
	</div>

    <h1>Egladil Benutzerverwaltung</h1>
	<h:form id="mainForm">
		<div id="messages">
			<h:messages globalOnly="true"
						showSummary="false"
        				showDetail="true"
        				layout="table"
						errorClass="errorMessages"
						infoClass="infoMessages"/>
		</div>
		<div id="content">
			<ui:insert name="content" />
		</div>
	</h:form>
</h:body>
</html>